### PR TITLE
17 lesson - objects

### PR DESCRIPTION
**Pull request by NadezhdaBabenko**
Hey!
We "prepared" a lesson about Objects. I just used the old presentation from the previous course (because it was really great, I think) and add some new slides with theory. And we also want to give some class work after it.

### CODE REVIEW

**Comment by oktupol** [comment]
These `.DS_Store` files are system files by Macintosh and shouldn't be in the repository. Can you exclude them from git? For that you need to perform following commands:

- First, add them to the .gitignore file in the project root. There is none yet, but that doesn't matter, because following command will create it with the record you need: `echo '**/.DS_Store' >> .gitignore`
- Then, in each directory containing such a file, execute `git rm --cached .DS_Store`
- Finally, `git add -A`, `git commit` and `git push`

**Comment by NadezhdaBabenko** [comment]
@oktupol thanks! I did that you wrote!

**Review by MrTim — COMMENTED** [review]
@NadezhdaBabenko @golovnevs slides are fine for me! interesting part is what you guys plan for the class work? :)

**Comment by NadezhdaBabenko** [comment]
We prepared one task for students. We want to split them for 4 groups (3 person in each group): 

1. Create a simple page, using bootstrap, to display online store
2. Come up with one type of product that you will sell (ex. books, cars, dresses etc. )
3. Create array of 4 object, where each object is description of your item.

  * All objects should have the same structure
  * Each object must have at least 4 attributes and 1 nested object

4.Display all your objects on a web-page
 using loop or forEach.


If you feel ready to challenge - bonus! 

Make it with promse which return an array of objects as a result.

 Array example:
 
 let cars = [{
   car: "Seat Leon",
   imgSrc:'/images/seat.jpg',
   colour: "red",
   price: 25000,
   condition: {
     year: 2019,
     mileage: 12000,
     mileageUnit: "km"
   },
   {
   car: "Renault Clio",
   imgSrc:'images/renault.jpg',
   colour: "orange",
   price: 20000,
   condition: {
     year: 2020,
     mileage: 7000,
     mileageUnit: "km"
     },
   
    ...

 ];

**Comment by keponk** [comment]
hey this sounds super fun! ^^
just curious about this:
- are they expected to create a design during the class or do we give them one (i mean a general design like a wireframe)
- if they go for the extra challenge, i understood they would create the pure promise and insde of it return the data from the array. But it might be confusing since they've been using "fetch" and you need to point that somewhere. If there's data I could help creating a quick api for them.

**Comment by golovnevs** [comment]
Hi! We didn't plan to provide students with a template, to check how they can work with bootstrap. Do you think it would be better to prepare a template for students?
Part of the task with the promis is only for those who feel like a superhero :) To solve it, students should create a fake API using promis and array, if I understood correct  @MrTim

**Comment by MrTim** [comment]
> hey this sounds super fun! ^^
> just curious about this:
> 
>     * are they expected to create a design during the class or do we give them one (i mean a general design like a wireframe)
> 
>     * if they go for the extra challenge, i understood they would create the pure promise and insde of it return the data from the array. But it might be confusing since they've been using "fetch" and you need to point that somewhere. If there's data I could help creating a quick api for them.

@keponk the idea with Promise is just for them to practice with it. We talked about it and it's super important to understand what you can do with it. And the other point: with this you can actually simulate the fetch, because Promise will give you the data.

**Review by MrTim — APPROVED** [review]

**Pull request merged**
